[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_pool = "5hAL4bQNPvwrmJBUngjP7yH6sMrKiTL9rLNRMCARMRqv"

[programs.devnet]
shadow_pool = "5hAL4bQNPvwrmJBUngjP7yH6sMrKiTL9rLNRMCARMRqv"

[programs.mainnet]
shadow_pool = "5hAL4bQNPvwrmJBUngjP7yH6sMrKiTL9rLNRMCARMRqv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/shadow-pool"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
